### ISSUE TITLE
Testing the backend

### ISSUE THREAD

**Issue by andrewbaldwin44** [aaspinwall/collab#101]
**What do you propose we work on? Please describe.**

Follow the example in `routes/voters/voters.test,js` and try out your hand in unit testing! We should have tests for our `addRoom` mutation and our `roomByID` query.

**Comment by cangoman** [comment]
I can give this one a go

**Comment by aaspinwall** [comment]
> I can give this one a go

Fire away!

**Comment by cangoman** [comment]
@aaspinwall close this close this 😛

**Comment by aaspinwall** [comment]
Closed on #134
