### ISSUE TITLE
Document backend

### ISSUE THREAD

**Issue by aaspinwall** [aaspinwall/collab#12]
Add a readme file in the backend folder that explains how the API works. Please also comment your sample code for those of us who aren't familiar with graphql

**Comment by aaspinwall** [comment]
I updated the [readme](https://github.com/aaspinwall/collab/blob/main/backend/README.md) with some sample questions. Please fill it in.

**Comment by ShaiGilboa** [comment]
I've just changed the package.json in the backend and root to accommodate that, see if this is what you meant.
once merged we can start defining the files

**Comment by ShaiGilboa** [comment]
for now, I think that `server.js` just serves the backend - bundles everything together and sends them on thier merry way :)

**Comment by andrewbaldwin44** [comment]
Done!
