### ISSUE TITLE
Timer Component

### ISSUE THREAD

**Issue by kolbymckeown** [aaspinwall/collab#34]
In the 'helpers' folder, create a component which:

- Takes a prop "time" (in seconds - default should be 180) 
- Will display a count down
- When the timer is finished there should be an alert

_Don't worry about styling for now_

**Comment by aaspinwall** [comment]
![Seal of approval](https://media.giphy.com/media/13zeE9qQNC5IKk/giphy.gif)

**Comment by aaspinwall** [comment]
If we can add screenshots and/or references it would be easier for contributors to pick up

**Comment by CarlosFabianG** [comment]
Hello, I would like to try this one :-)

**Comment by aaspinwall** [comment]
> Hello, I would like to try this one :-)

Go for it. Thanks!
