### ISSUE TITLE
Make a shareable link component

### ISSUE THREAD

**Issue by aaspinwall** [aaspinwall/collab#35]
Make a component so we can share our room link easily.

It should:

- Take text as props
- When you click the icon, it copies the text to the clipboard
- Fires a callback when the text has been copied

![N](https://user-images.githubusercontent.com/17233773/100683038-7b572200-3345-11eb-9e84-3a6e6e321f95.png)

_Don't worry about the styling. Functionality is key._

**Comment by LeonardPoissant** [comment]
Let me contribute !

**Comment by aaspinwall** [comment]
> Let me contribute !

You got it
