### ISSUE TITLE
Countdown Animation

### ISSUE THREAD

**Issue by kolbymckeown** [aaspinwall/collab#44]
Have a countdown animation around the timer like in the Figma, something that looks like: 
![image](https://user-images.githubusercontent.com/62035359/101104429-1431ab80-3599-11eb-8844-dade5b18b793.png)
The animation should be relative to how much long the timer is.

**Comment by CarlosFabianG** [comment]
I'll work on this

**Comment by aaspinwall** [comment]
Closed on #108
