### ISSUE TITLE
Button component

### ISSUE THREAD

**Issue by aaspinwall** [aaspinwall/collab#70]
Make a **nice nice nice nice** component that roughly matches the screenshot

It should take text or children and styles as props.

![Screen Shot 2020-12-10 at 6 12 20 PM](https://user-images.githubusercontent.com/17233773/101841118-52881700-3b13-11eb-8ecb-75f86e303666.png)

**Comment by AlexandreGagnon-Lalonde** [comment]
Alright, let me start with something not too complicated to get used to the application!

**Comment by aaspinwall** [comment]
All yours 

> Alright, let me start with something not too complicated to get used to the application!

**Comment by aaspinwall** [comment]
Closed on #94
