### ISSUE TITLE
style "create-a-room" page to match Figma design

### ISSUE THREAD

**Issue by kolbymckeown** [aaspinwall/collab#73]
Style the current "create-a-room" page to match the following designs:
(the buttons can have basic styling, they will be overwritten when we have an individual button component)
![image](https://user-images.githubusercontent.com/62035359/101964144-63ea2580-3bde-11eb-8bdd-2b0de7f36541.png)

and once "Submit" is hit, the "Invite your friends" should appear:
![image](https://user-images.githubusercontent.com/62035359/101964154-72384180-3bde-11eb-90cf-7becd9c715f9.png)

**Comment by AlexandreGagnon-Lalonde** [comment]
I'll work on that one!

**Comment by Edu93Jer** [comment]
@aaspinwall I guess @AlexandreGagnon-Lalonde will work on that too, is ok no problem actually here are some links that you can use for the share buttons https://github.com/bradvin/social-share-urls/blob/master/code/javascript/javascript/social-share-media.js

**Comment by aaspinwall** [comment]
Closed [here](https://github.com/aaspinwall/collab/commit/b21bead3569c5707de75814e8878617bb82630fc)
