### ISSUE TITLE
Random Id Generator

### ISSUE THREAD

**Issue by kolbymckeown** [aaspinwall/collab#74]
Create a helper function that when it is ran, **returns** a four number/letter string, this will be used as individual room Id's
Example Ids: "A4EB", "44CQ", 8F2X", etc...

**Comment by andrewbaldwin44** [comment]
@scorpiocavalier

**Comment by cangoman** [comment]
I can get on this

**Comment by aaspinwall** [comment]
> I can get on this

You got it!

**Comment by aaspinwall** [comment]
Closed by #96
