### ISSUE TITLE
create Form for voting choices

### ISSUE THREAD

**Issue by kolbymckeown** [aaspinwall/collab#75]
Create the Form to match the Figma design, it should accept "voteOptions" and "timeLimit" as props:
The user should only be able to select one option for the time being.
The "Submit" button should simply fire off a page alert() with the users choice for now
![image](https://user-images.githubusercontent.com/62035359/101964398-3a7dc980-3bdf-11eb-83f9-e109f87252f2.png)

**Comment by LeonardPoissant** [comment]
I can tackle this.

**Comment by aaspinwall** [comment]
How is this going?

**Comment by LeonardPoissant** [comment]
Oops, I thought I pushed it last week. Quick reviewing and shipping it.

**Comment by aaspinwall** [comment]
Closed on #123
