### ISSUE TITLE
Empty input should not be permitted

### ISSUE THREAD

**Issue by aaspinwall** [aaspinwall/collab#79]
**How to reproduce**
If the input is empty and you click the button, the time goes to zero immediately.

**Expected behaviour**
Error message: "Field is required"
(the error message text can be passed as props)

This is related to #34 and #45 

<img width="308" alt="Screen Shot 2020-12-12 at 11 56 55 AM" src="https://user-images.githubusercontent.com/17233773/101989861-30a4a680-3c71-11eb-9f90-cbcae6c1a217.png">

**Comment by fakoredeDamilola** [comment]
I will like to try this

**Comment by aaspinwall** [comment]
> I will like to try this

You got it. Thanks!

**Comment by fakoredeDamilola** [comment]
Hey
Please I tried running npm install on the frontend directory but everytime I do that, I get this error. Please what is going on. I am actually  working on nextJS personally and this does not occur. But this happens everytime I clone a repo and try to work on it.
I am able to run `npm install` on the backend but not frontend
![Screenshot (1795)](https://user-images.githubusercontent.com/47531232/102440550-baad9000-4020-11eb-9cbc-0ee748549384.png)

**Comment by aaspinwall** [comment]
> Hey
> Please I tried running npm install on the frontend directory but everytime I do that, I get this error. Please what is going on. I am actually working on nextJS personally and this does not occur. But this happens everytime I clone a repo and try to work on it.
> I am able to run `npm install` on the backend but not frontend
> ![Screenshot (1795)](https://user-images.githubusercontent.com/47531232/102440550-baad9000-4020-11eb-9cbc-0ee748549384.png)

Try running npm start on the root directory. That will install all the dependencies and start frontend and backend servers.

**Comment by fakoredeDamilola** [comment]
HI,
I cloned it again from your repo and ran `npm start` on the home directory and I got this error
![Screenshot (1797)](https://user-images.githubusercontent.com/47531232/102454501-67e2d100-403e-11eb-927d-6f0bc9c5e126.png)

**Comment by aaspinwall** [comment]
> HI,
> I cloned it again from your repo and ran `npm start` on the home directory and I got this error
> ![Screenshot (1797)](https://user-images.githubusercontent.com/47531232/102454501-67e2d100-403e-11eb-927d-6f0bc9c5e126.png)

Okay. Run ```npm install``` on the root directory. I'f that doesn't work, try ```npm install npm-run-all --save-dev``` and install again. That should do the trick

**Comment by fakoredeDamilola** [comment]
> Hey
> Please I tried running npm install on the frontend directory but everytime I do that, I get this error. Please what is going on. I am actually working on nextJS personally and this does not occur. But this happens everytime I clone a repo and try to work on it.
> I am able to run `npm install` on the backend but not frontend
> ![Screenshot (1795)](https://user-images.githubusercontent.com/47531232/102440550-baad9000-4020-11eb-9cbc-0ee748549384.png)

Good day,
I think you need to unassign me to this issue, I tried everything that you said but I still get this same error when it start installing for the front end.
I ran `npm install npm-run-all --save-dev` and then ran npm run start
it installed the backend but for the frontend, it installed some for like 15 mins and the error started

This is my first time trying to contribute to open source and I am guessing the problem is with my laptop. Like I said this is not the pnly project I had this issue with.

**Comment by aaspinwall** [comment]
I'm so sorry to 

> > Hey
> > Please I tried running npm install on the frontend directory but everytime I do that, I get this error. Please what is going on. I am actually working on nextJS personally and this does not occur. But this happens everytime I clone a repo and try to work on it.
> > I am able to run `npm install` on the backend but not frontend
> > ![Screenshot (1795)](https://user-images.githubusercontent.com/47531232/102440550-baad9000-4020-11eb-9cbc-0ee748549384.png)
> 
> Good day,
> I think you need to unassign me to this issue, I tried everything that you said but I still get this same error when it start installing for the front end.
> I ran `npm install npm-run-all --save-dev` and then ran npm run start
> it installed the backend but for the frontend, it installed some for like 15 mins and the error started
> 
> This is my first time trying to contribute to open source and I am guessing the problem is with my laptop. Like I said this is not the pnly project I had this issue with.

I'm so sorry to hear that. I'll try to reproduce your problem on a fresh install. Thanks for your effort, we appreciate it!

**Comment by AlexandreGagnon-Lalonde** [comment]
I can try to tackle this one!

**Comment by aaspinwall** [comment]
You got it!

> I can try to tackle this one!

**Comment by aaspinwall** [comment]
Closes #95
