### ISSUE TITLE
Implement random ID generation

### ISSUE THREAD

**Issue by andrewbaldwin44** [aaspinwall/collab#97]
**What do you propose we work on? Please describe.**

In the `rooms.resolver.js`, the `addVoterToRoom`currently takes a roomID as argument. We can now replace this with the generated ID.

**Comment by cangoman** [comment]
Well while I'm on it... I can give this one a go 👍

**Comment by andrewbaldwin44** [comment]
Awesome!! You got it!

**Comment by aaspinwall** [comment]
Functionality merged on #96

**Comment by aaspinwall** [comment]
Do you want to implement it on the create a room page? @cangoman

**Comment by cangoman** [comment]
Well, we only need to remove it from the form right? Cause we generate it in the backend and don't need to show it to the user when creating the room

**Comment by aaspinwall** [comment]
> Well, we only need to remove it from the form right? Cause we generate it in the backend and don't need to show it to the user when creating the room

Yessir, that's it. Do you wanna tackle that?

**Comment by cangoman** [comment]
Sure, I got it

**Comment by aaspinwall** [comment]
Closed by #111
