### ISSUE TITLE
User name generator screen

### ISSUE THREAD

**Issue by aaspinwall** [aaspinwall/collab#98]
**Why?**
When the user opens the link to a room, they should pick a name. The name should be generated by taking two random words from our word bank. These should be displayed for the user to select, they can also shuffle to get more suggestions. Once they pick one, the other options should be displayed as inactive. When the user is happy with their choice, they hit NEXT and can move on. 

You can use a new page such as ```pages/name-generator/``` to show how it works and we can later implement it on the app flow.

The result should look like this:

<img width="298" alt="Screen Shot 2020-12-20 at 12 00 05 PM" src="https://user-images.githubusercontent.com/17233773/102719252-04190c00-42bb-11eb-86db-b983d9ae4f95.png">

The code on issue #38 has most of the work done, we need

**Comment by AlexandreGagnon-Lalonde** [comment]
I volunteer as a tribute

**Comment by aaspinwall** [comment]
> I volunteer as a tribute

This made me laugh out loud. Go for it!

**Comment by aaspinwall** [comment]
Merged on #106
